### ISSUE TITLE
Access to project with image

### ISSUE THREAD

**Issue by grantoconnor** [tfrantzen/gcp-ml-walkthrough#2]
Hi tfrantzen 

I work for Datacom in NZ, who requested access to your code, thank you for sharing it!

I'm unable to access the project where the customised Debian image is located (project=eip-images), are you able to allow access (compute.imageUser) to my test account grantoconnor@gforceuniverse.com ?

Thanks
Grant

**Comment by tfrantzen** [comment]
Hi Grant!

I recently committed a change fixing the image type and project. Sorry about that!

Regards,
Tom

**Comment by tfrantzen** [comment]
gcloud beta compute --project=$(gcloud config get-value project) instances create speech-client --zone=us-east1-b --machine-type=n1-standard-1 --subnet=default --scopes=https://www.googleapis.com/auth/cloud-platform --tags=https-server --image=debian-9-stretch-v20180611 --image-project=debian-cloud --boot-disk-size=10GB --boot-disk-type=pd-standard --boot-disk-device-name=speech-client

**Comment by grantoconnor** [comment]
Thanks for sorting it so quickly.

Have a great day 😀

Regards
Grant
